version: '3.8'

services:
  portfolio:
    image: portfolio:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9520:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`dheeraj.mooh.me`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"
      - "traefik.http.services.portfolio.loadbalancer.server.port=3000"
    environment:
      - NODE_ENV=production
    networks:
      - dokploy-network
    volumes:
      # Mount the local folder to 'overrides' instead of 'public'
      # The entrypoint.sh script will merge these files into 'public' at startup
      - /home/ubuntu/portfolio:/app/overrides

networks:
  dokploy-network:
    external: true
